### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by bartlomn** [tuenti/activity-detector#2]
As much as I dislike doing that, I need to use your lib (thanks for the work) with IE8.
There's not much required to make it happen, only issue is lack of `addEventListener`.
I am inclined to PR a fix.

**Comment by atabel** [comment]
Why don't you use an `addEventListener` polyfill for IE8?

**Comment by bartlomn** [comment]
Usually I would, but our project is "special" - it that we are targeting IE8 as main platform (don't ask... :/) and they want us to avoid messing with polyfills if possible. And you're right, my case is kind of an edge case here so no point fixing what's not broken in the main codebase.
