### ISSUE TITLE
Remove `blur` from inactivityEvents

### ISSUE THREAD

**Issue by aesopwolf** [tuenti/activity-detector#6]
What's the best way to remove 'blur' from the inactivityEvents array?

Would you be willing to accept a PR that adds this feature? Maybe via `inactivityEvents: undefined`?

I'd prefer to not "short-circuit" the `timeToIdle` timeout.

**Comment by aesopwolf** [comment]
I think this might actually have more to do with the page visibility. So, what would be the best way to not automatically fire the idle event when the tab is hidden?

**Comment by atabel** [comment]
You can configure the events which transition to "active"/"idle". take a look at [advanced options](https://github.com/tuenti/activity-detector#advanced-options)

**Comment by Ekotlikoff** [comment]
I was able to stop blurs from triggering idle by setting { inactivityEvents: null }, but { inactivityEvents: [] } is not working.

**Comment by pladaria** [comment]
After a quick look to the code (not tested soy I might be wrong)

Maybe the `idle` state was triggered by the `visibilityChangeEvent` instead of `blur`.
By setting `inactivityEvents` to `null` you might be preventing the handling of visibilityChange by throwing an exception (trying to iterate a null value).

**Comment by mikerogne** [comment]
Yeah I'm also experiencing the same thing. inactivityEvents: [] ... but it still goes 'away'/'inactive' when I switch tabs.

**Comment by mikerogne** [comment]
This is how I addressed it:

`const handleVisibilityChangeEvent = () => {
        if (document[hidden]) {
            if (inactivityEvents.indexOf('blur') !== -1) {
                setState(IDLE);
            }
        } else {
            if (activityEvents.indexOf('focus') !== -1) {
                setState(ACTIVE);
            }
        }
    };`

**Comment by paulg446** [comment]
same issue as @mikerogne. Switching tabs changes to idle despite setting inactivityEvents: []

**Comment by SergioMorchon** [comment]
Related with [this PR](https://github.com/tuenti/activity-detector/pull/9), should be solved

**Comment by jdexyz** [comment]
This does not work for me. However, setting `inactivityEvents: ['']` does work.
